{
 "title": "SenseOps server details",
 "description": "Performance metrics, warnings and errors per server",
 "tags": [ "senseops" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "show tag values from \"apps\" with key IN (\"server_description\")"
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Warnings & Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warnings",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "warnings" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "log_level", "operator": "=", "value": "WARN" },
        { "condition": "AND", "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "log_level", "operator": "=", "value": "ERROR" },
        { "condition": "AND", "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "server",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU load",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM: [[server]]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "RAM (free)",
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Users (total)",
       "measurement": "users",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Users (active)",
       "measurement": "users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 17, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "Cache lookups",
       "measurement": "cache",
       "select": [
        [
         { "params": [ "lookups" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Cache hit ratio",
       "measurement": "cache",
       "select": [
        [
         { "params": [ "hits" ], "type": "field" },
         { "params": [ " / lookups" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded apps",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "alias": "In memory docs",
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Server uptime",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Server uptime",
       "measurement": "sense_server",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "QIX engine",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 5, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Calls",
       "measurement": "apps",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Selections",
       "measurement": "apps",
       "select": [
        [
         { "params": [ "selections" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Apps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "In memory",
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Loaded",
       "measurement": "apps",
       "select": [
        [
         { "params": [ "loaded_docs_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Active",
       "measurement": "apps",
       "select": [
        [
         { "params": [ "active_docs_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Warnings & Errors",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" },
        { "params": [ "log_level" ], "type": "tag" },
        { "params": [ "source_process" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded apps",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "server_name" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "server_name" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "loaded_docs" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "server_name" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "active_docs" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}