{
 "title": "SenseOps dashboard (Butler SOS 9.2)",
 "description": "Operational metrics for Qlik Sense",
 "tags": [ "senseops" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Main metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stockholm",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Users per server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "user_session_details",
     "select": [
      [
       { "params": [ "user_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy sessions per server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "user_session_details",
     "select": [
      [
       { "params": [ "session_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warnings during last hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "Warnings during last hour",
     "measurement": "log_event",
     "query": "SELECT count(\"message\") AS \"Errors\" FROM \"10d\".\"log_event\" WHERE (\"level\" = 'WARN') AND (time > (now() - 1h)) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       { "params": [ "Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "WARN" }
     ]
    }
   ]
  },
  {
   "title": "Errors during last hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "Errors during last hour",
     "measurement": "log_event",
     "query": "SELECT count(\"message\") AS \"Errors\" FROM \"10d\".\"log_event\" WHERE (\"level\" = 'ERROR') AND $timeFilter GROUP BY time(60m) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       { "params": [ "Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "ERROR" }
     ]
    }
   ]
  },
  {
   "title": "Apps in memory",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apps",
     "select": [
      [
       { "params": [ "in_memory_docs_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique users (current hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "user_events",
     "select": [
      [
       { "params": [ "userFull" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique users (last 15 min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "user_events",
     "select": [
      [
       { "params": [ "userFull" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free RAM per server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_server_description",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "server_description" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU load per server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "$tag_server_description",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server_description" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User sessions per virtual proxy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server_description $tag_user_session_virtual_proxy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "user_session_virtual_proxy" ], "type": "tag" },
      { "params": [ "server_description" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "user_session_summary",
     "select": [
      [
       { "params": [ "session_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User events per 1 min window, by event type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_event_action",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "event_action" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_events",
     "select": [
      [
       { "params": [ "userId" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User events per 1 min window, by event origin",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_origin",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "origin" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_events",
     "select": [
      [
       { "params": [ "userId" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Apps in memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Normal apps",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_names" ], "type": "field" },
         { "params": [ "Apps in RAM" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Session apps",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_session_docs_names" ], "type": "field" },
         { "params": [ "Session apps in RAM" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Users & Sessions per server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Users",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 22 },
     "repeat": "server",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_server_description: Total users",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_server_description: Active users",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Unique users (per 15 min)",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 22 },
     "targets": [
      {
       "alias": "User",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" }
       ],
       "measurement": "user_events",
       "select": [
        [
         { "params": [ "userFull" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 28 },
     "repeat": "server",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_server_description: Sessions",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "User events (table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "User events",
     "type": "table",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "origin" ], "type": "tag" },
        { "params": [ "event_action" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "user_events",
       "select": [
        [
         { "params": [ "userFull" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings & Errors (charts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Warnings per minute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_host $tag_source",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "level" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "level", "operator": "=", "value": "WARN" }
       ]
      }
     ]
    },
    {
     "title": "Errors per minute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "level" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "level", "operator": "=", "value": "ERROR" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings & Errors (table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Warnings & Errors",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "level" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "subsystem" ], "type": "tag" },
        { "params": [ "user_full" ], "type": "tag" },
        { "params": [ "task_name" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Qlik Sense errors and warnings",
     "type": "logs",
     "description": "Max 1000 rows are shown",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "limit": "1000",
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "raw_event" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Butler SOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Butler SOS memory use",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "alias": "Heap total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "butlersos_memory_usage",
       "select": [
        [
         { "params": [ "heap_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Heap used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "butlersos_memory_usage",
       "select": [
        [
         { "params": [ "heap_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Process memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "butlersos_memory_usage",
       "select": [
        [
         { "params": [ "process_memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "External memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "butlersos_memory_usage",
       "select": [
        [
         { "params": [ "external" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}