{
 "title": "SenseOps dashboard by Butler SOS",
 "description": "High level metrics for Qlik Sense",
 "tags": [ "senseops" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "show tag values from \"apps\" with key IN (\"server_description\")"
   },
   {
    "name": "virtual_proxy",
    "query": "show tag values from \"user_session_details\" with key IN (\"user_session_virtual_proxy\")"
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Main metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "New York", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 } },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
     "content": "<br>\n<br>\n<h2 style=\"text-align:center;\">Sessions</h1>\n<p style=\"text-align:center;\">Last 5 min</p>\n"
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "user_session_details",
       "select": [
        [
         { "params": [ "session_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=", "value": "/sales" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "user_session_details",
       "select": [
        [
         { "params": [ "session_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=", "value": "/sourcing" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "user_session_details",
       "select": [
        [
         { "params": [ "session_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=", "value": "/finance" }
       ]
      }
     ]
    },
    {
     "title": "Apps in memory per server/engine",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_server_description",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    { "title": "Stockholm", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 } },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 2, "x": 5, "y": 5 },
     "content": "<br>\n<br>\n<h2 style=\"text-align:center;\">Users</h1>\n<p style=\"text-align:center;\">Last 5 min</p>\n"
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "user_session_details",
       "select": [
        [
         { "params": [ "user_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=", "value": "/sales" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "user_session_details",
       "select": [
        [
         { "params": [ "user_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=", "value": "/sourcing" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "user_session_details",
       "select": [
        [
         { "params": [ "user_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=", "value": "/finance" }
       ]
      }
     ]
    },
    {
     "title": "User sessions per virtual proxy",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" }
       ],
       "measurement": "user_session_summary",
       "select": [
        [
         { "params": [ "session_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=~", "value": "/^$virtual_proxy$/" }
       ]
      }
     ]
    },
    {
     "title": "Free RAM per server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU load per server (5 min avg)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Apps in memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Normal apps",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_names" ], "type": "field" },
         { "params": [ "Apps in RAM" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Session apps",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_session_docs_names" ], "type": "field" },
         { "params": [ "Session apps in RAM" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Users & Sessions per server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users on [[server]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "repeat": "server",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total users",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Active users",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Users on [[server]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total users",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Active users",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Users on [[server]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total users",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Active users",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "active" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Sessions on [[server]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "repeat": "server",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Sessions on [[server]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Sessions on [[server]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings & Errors (charts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warnings",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "warnings" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "log_level", "operator": "=", "value": "WARN" },
        { "condition": "AND", "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "log_level", "operator": "=", "value": "ERROR" },
        { "condition": "AND", "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings & Errors (table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warnings & Errors",
     "type": "table-old",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" },
        { "params": [ "log_level" ], "type": "tag" },
        { "params": [ "source_process" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Butler SOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Butler SOS memory use",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "Process memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "butlersos_memory_usage",
       "select": [
        [
         { "params": [ "process_memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "butler_sos_instance", "operator": "=", "value": "DEV" }
       ]
      },
      {
       "alias": "Heap total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "butlersos_memory_usage",
       "select": [
        [
         { "params": [ "heap_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Heap used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "butlersos_memory_usage",
       "select": [
        [
         { "params": [ "heap_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free RAM: Central",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=", "value": "Central" }
       ]
      }
     ]
    },
    {
     "title": "Free RAM: Dev1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=", "value": "Dev1" }
       ]
      }
     ]
    },
    {
     "title": "Free RAM: Access1",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=", "value": "Access1" }
       ]
      }
     ]
    },
    {
     "title": "Apps in memory: Central",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_names" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=", "value": "Central" }
       ]
      }
     ]
    },
    {
     "title": "Apps in memory: Dev1",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_names" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=", "value": "Dev1" }
       ]
      }
     ]
    },
    {
     "title": "Apps in memory: Access1",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "apps",
       "select": [
        [
         { "params": [ "in_memory_docs_names" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=", "value": "Access1" }
       ]
      }
     ]
    }
   ]
  }
 ]
}