{
 "title": "SenseOps Overview",
 "description": "High level metrics for Qlik Sense",
 "tags": [ "senseops" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "show tag values from \"apps\" with key IN (\"server_description\")"
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  {
   "title": "User sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current sessions per virtual proxy",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "$tag_user_session_virtual_proxy",
       "groupBy": [
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" }
       ],
       "measurement": "user_session_summary",
       "select": [
        [
         { "params": [ "session_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "User sessions per virtual proxy",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" }
       ],
       "measurement": "user_session_summary",
       "select": [
        [
         { "params": [ "session_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Unique sessions by user (past 5 min)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "($tag_user_session_virtual_proxy) $tag_user_session_user_id",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "user_session_user_id" ], "type": "tag" },
        { "params": [ "user_session_virtual_proxy" ], "type": "tag" }
       ],
       "measurement": "user_session_details",
       "query": "SELECT count(distinct(\"session_id\")) FROM \"user_session_details\" WHERE (time > now()-5m) GROUP BY \"user_session_user_id\", \"user_session_virtual_proxy\"",
       "select": [
        [
         { "params": [ "session_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Unique sessions by user, per 15 min (/hdr endpoint)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "alias": "$tag_user_session_user_id",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "user_session_user_id" ], "type": "tag" }
       ],
       "measurement": "user_session_details",
       "query": "SELECT count(distinct(\"user_id\")) FROM \"user_session_details\" WHERE (\"user_session_virtual_proxy\" = '/hdr') AND $timeFilter GROUP BY \"user_session_user_id\"",
       "select": [
        [
         { "params": [ "session_id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "user_session_virtual_proxy", "operator": "=", "value": "/hdr" }
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  { "title": "RAM usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "[[server]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "repeat": "server",
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_server_description]]",
     "groupBy": [
      { "params": [ "server_description" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "[[server]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_server_description]]",
     "groupBy": [
      { "params": [ "server_description" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "[[server]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_server_description]]",
     "groupBy": [
      { "params": [ "server_description" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "[[server]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_server_description]]",
     "groupBy": [
      { "params": [ "server_description" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "users",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ],
        [
         { "params": [ "active" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Sessions by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "[[server]]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "repeat": "server",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "[[server]]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "[[server]]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "[[server]]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Sessions",
       "measurement": "session",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings & Errors (charts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "info" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "log_level", "operator": "=", "value": "INFO" },
        { "condition": "AND", "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Warnings",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "warnings" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "log_level", "operator": "=", "value": "WARN" },
        { "condition": "AND", "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_server_description]]",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "log_level", "operator": "=", "value": "ERROR" },
        { "condition": "AND", "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings & Errors (table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warnings & Errors",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "server_description" ], "type": "tag" },
        { "params": [ "log_level" ], "type": "tag" },
        { "params": [ "source_process" ], "type": "tag" }
       ],
       "measurement": "log_event",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server_description", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}