name: OSV-Scanner Scheduled Scan

on:
    workflow_dispatch:
    schedule:
        # Run daily at 02:00 UTC (03:00 CET)
        - cron: '0 2 * * *'
    # Also run on push to master branch
    push:
        branches: [master]

permissions:
    # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
    actions: read
    # Require writing security events to upload SARIF file to security tab
    security-events: write
    # Only need to read contents
    contents: read

jobs:
    scan-scheduled:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Run scanner
              uses: google/osv-scanner-action/osv-scanner-action@c5996e0193a3df57d695c1b8a1dec2a4c62e8730 # v2.3.3
              with:
                  scan-args: |-
                      --output=results.json
                      --format=json
                      -r
                      ./
              continue-on-error: true

            - name: Run osv-scanner-reporter
              uses: google/osv-scanner-action/osv-reporter-action@c5996e0193a3df57d695c1b8a1dec2a4c62e8730 # v2.3.3
              with:
                  scan-args: |-
                      --output=results.sarif
                      --new=results.json
                      --gh-annotations=false
                      --fail-on-vuln=true

            - name: Upload artifact
              id: upload_artifact
              if: ${{ !cancelled() }}
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                  name: SARIF file
                  path: results.sarif
                  retention-days: 5

            - name: Upload to code-scanning
              if: ${{ !cancelled() }}
              uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
              with:
                  sarif_file: results.sarif

            - name: Print Code Scanning URL
              if: ${{ !cancelled() }}
              run: |
                  echo "View the OSV-Scanner results in the 'Security' tab, using the following link:"
                  echo "${{ github.server_url }}/${{ github.repository }}/security/code-scanning?query=is%3Aopen+branch%3A${{ github.ref_name }}+tool%3Aosv-scanner"

            - name: Error troubleshooter
              if: ${{ always() && steps.upload_artifact.outcome == 'failure' }}
              run: |
                  echo "::error::Artifact upload failed. This is most likely caused by a error during scanning earlier in the workflow."
                  exit 1
